# youtube logo
import turtle as t
t.pen(pencolor="red",pensize=35,speed=2)
t.fillcolor("red")
t.begin_fill()
t.goto(90,0)
t.goto(90,50)
t.goto(0,50)
t.goto(0,0)
t.end_fill()
t.penup()
t.goto(30,5)
t.pendown()
t.pen(pencolor="red",pensize=1,speed=2)
t.color("red")
t.fillcolor("white")
t.begin_fill()
t.goto(30,47)
t.goto(65,25)
t.goto(30,5)
t.end_fill()
t.penup()
t.goto(0,-60)
t.pendown()
t.pencolor("black")
t.write("YouTube",font=("Franklin Gothic Demi Cond",24,"normal"))
t.done()